title: Tarry
description: Tampereen Rytmipelaajat ry
url: "https://tarry.fi"
baseurl: ""
data_dir: _data
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
exclude:
  - doc/
