remote_theme: jekyll/minima
title: Tarry
description: Tampereen rytmipelaajat ry
url: "https://tarry.fi"
baseurl: ""
minima:
  skin: dark
nav:
  - title: Home
    url: /
  - title: Rhythm Games
    url: /rytmipelit/
  - title: Association
    url: /yhdistys/
  - title: Contact
    url: /yhteystiedot/
